repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: fmt
      - id: clippy
  - repo: local
    hooks:
      - id: cargo-readme
        name: cargo-readme
        entry: just generate-readme
        language: system
        pass_filenames: false
      - id: cargo-doc
        name: cargo-doc
        entry: just generate-doc
        language: system
        pass_filenames: false