[package]
name = "van-genuchten"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.7"
num-traits = { version = "^0.2", default-features = false, features = ["libm"] }
nutype = "0.4.0"
thiserror = { version = "1.0", package = "thiserror-core", default-features = false }
